server:
  port: 9191

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5435/toi_db_fresh}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:toi_user}
    password: ${DB_PASSWORD:toi_pass}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86400000
  refresh-expiration: 604800000

uploads:
  dir: ${UPLOAD_DIR:uploads}
  public-url: ${UPLOAD_PUBLIC_URL:http://localhost:9191}

threads:
  client-id: ${THREADS_CLIENT_ID:1241875974190861}
  client-secret: ${THREADS_CLIENT_SECRET:0ef7185cc8f2d0347ef83a28b8db3b36}
  redirect-uri: ${THREADS_REDIRECT_URI:https://toi.com.kz/auth/callback}
